[package]
name = "Rusty-System-Analyser"
version = "0.10.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
winapi = { version = "0.3.9", features = ["winbase", "fileapi", "ntdef", "winnt"] }
sysinfo = "0.33.0"
walkdir = "2.3"
ctrlc = "3.4.5"
chrono = "0.4"
rayon = "1.5"
twox-hash = "2.1.0"