[package]
name = "Rusty-System-Analyser"
version = "6.9.42"
edition = "2021"

[dependencies]
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
walkdir = "2.3"
sysinfo = "0.33.0"
